# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c797666344800cd895a0ceae1eebd33947ac03036248983e28494b9165e8e3a4e8f96ea439d6b195fee8ef6c7eab2b9a79f803bf6f2a99c2b1326539ec4ef4b2

test:
  secret_key_base: 6dfc9d21f0e06ac5bc6a9c184383eb345b5550f42f60ec056773e9ae2c321ef0f98526e591f46d983a93b827b2dcaf353df5ed5d3dc29ef6c15c20cf6fa166e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
